import { USER_ROLE } from '@/stores/authStore'

export const ACCOUNT_LIST_TEXTS = {
  kicker: '시스템 관리',
  title: '계정 및 권한 관리',
  tabStatus: '계정 및 권한 현황',
  tabRequests: '요청 및 승인',
  sectionAccountStatus: '근무자 계정 현황',
  sectionSiteDirectorAccounts: '현장 총 책임자',
  workerSubTabHQ: '본사 직영',
  workerSubTabByTrade: '공종별',
  tradeUnassigned: '공종 미지정',
  sectionRequests: '요청 및 승인',
  reload: '목록 새로고침',
  reloadBusy: '불러오는 중…',
  newAccount: '신규 계정 생성',
  colLoginId: '로그인 ID',
  colWorkerName: '근무자 명',
  colWorkerPhone: '근무자 휴대폰',
  colWorkerRole: '근무자 권한',
  colWorkerTrade: '근무자 공종',
  colName: '이름',
  colPhone: '휴대폰',
  colEmail: '이메일',
  colRole: '권한',
  colSite: '현장',
  colTrade: '공종',
  colStatus: '상태',
  colActions: '관리',
  colReqAt: '요청 일시',
  colReqTitle: '요청 제목',
  colReqRequesterRole: '요청자 권한',
  colReqStatus: '처리 상태',
  reqTypeCreate: '계정·권한',
  reqApprove: '승인',
  reqReject: '거절',
  noRequests: '접수된 요청이 없습니다.',
  demoRequestHint: '예시 데이터 — API로 처리되지 않습니다.',
  detailModalTitle: '요청 상세',
  lblDetailAt: '요청 일시',
  lblDetailSite: '현장명',
  lblDetailName: '요청자명',
  lblDetailRole: '요청자 권한',
  lblDetailTrade: '공종',
  lblDetailRequestedLoginId: '신규 계정 로그인 ID',
  lblDetailRequestedName: '신규 계정 이름',
  lblDetailRequestedRole: '신규 계정 권한',
  lblDetailSiteCode: '현장 코드',
  lblDetailRejectNote: '거절 사유',
  lblDetailBody: '요약·비고',
  active: '사용 중',
  inactive: '비활성',
  edit: '수정',
  activate: '활성',
  del: '비활성',
  lblAccountName: '계정명',
  modalCreate: '신규 계정 생성',
  modalEdit: '계정 수정',
  save: '저장',
  cancel: '취소',
  pwdNew: '비밀번호 (8자 이상)',
  loginIdRo: '로그인 ID는 수정할 수 없습니다.',
  modalApproveTitle: '요청 승인',
  modalRejectTitle: '요청 거절',
  labelInitialPwd: '초기 비밀번호 (선택)',
  approvePwdOptionalHint:
    '비워 두면 서버에서 임시 비밀번호를 자동 생성합니다. 직접 지정할 때만 8자 이상 입력하세요.',
  labelRejectNote: '거절 사유 (선택)',
  rolePickHint: '권한 선택',
  sitePick: '현장 명',
  pwdEditSectionTitle: '비밀번호 수정',
  pwdResetMail: '비밀번호 초기화',
  pwdResetMailAlert:
    '등록된 이메일로 비밀번호 재설정 메일을 발송했습니다.\n메일함을 확인해 주세요.',
  tradePick: '공종',
  tradeHint: '공종별 책임자·관리자만 선택',
  phone: '휴대폰 번호',
  email: '이메일',
  backToSites: '현장 목록',
  bulkComplete: '완료',
  bulkDismiss: '반려',
  reqDetailBtn: '상세보기',
  colReqDetail: '상세',
  bulkRejectModalTitle: '선택 요청 반려',
  bulkNoEligible: '대기 상태인 요청을 하나 이상 선택해 주세요.',
  srSelectColumn: '선택',
}

export const ACCOUNT_ROLE_OPTIONS = [
  { value: USER_ROLE.ADMIN, label: '시스템 관리자' },
  { value: USER_ROLE.HEADQUARTOR, label: '본사' },
  { value: USER_ROLE.SITE_MANAGER, label: '현장 관리자' },
  { value: USER_ROLE.SITE_DIRECTOR, label: '현장 총 책임자' },
  { value: USER_ROLE.SECTION_LEADER, label: '공종별 책임자' },
  { value: USER_ROLE.SECTION_SUPERVISOR, label: '공종별 현장 관리자' },
]

export const ACCOUNT_STATUS_THEAD_CLASS =
  'border-b border-violet-200/70 bg-violet-100/45 text-xs font-bold text-violet-950'
